
name: 'adventureworks'
version: '1.0.0'
config-version: 2

profile: 'adventureworks'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  adventureworks:
    sales:
      source: &source
        +materialized: table
      staging: &staging
        +materialized: table
      intermediate: &intermediate
        +materialized: ephemeral
      marts: &marts
        +materialized: table